### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by bw98** [Captain32/6.824#1]
是 NEU 的兄弟么？看到你的 csye6225 还有其他的一些东西哈哈，我之前也做了点 6.824，有兴趣加个 contact 么？不用怕泄露隐私啥的，私发我贴在 github 主页的 neu 邮箱就行

**Comment by Captain32** [comment]
> 是 NEU 的兄弟么？看到你的 csye6225 还有其他的一些东西哈哈，我之前也做了点 6.824，有兴趣加个 contact 么？不用怕泄露隐私啥的，私发我贴在 github 主页的 neu 邮箱就行

不是的，只是上了一下csye6225那门课😂

**Comment by bw98** [comment]
哈哈哈，居然还有其他学校的同学上这门课，good to know~
